spring.application.name=url-shortener-sb



spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerDb
spring.datasource.username=root
spring.datasource.password=Gaurav#26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=YkZrY0FvN2N1aE5pU3Z4ZUN0Y2d5eHNVQ2pFT2pSV0U=

jwt.expiration=172800000


logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG


frontend.url=http://localhost:5173